# Generated by Django 3.0.5 on 2020-06-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0002_remove_entrega_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
