# Generated by Django 3.0.5 on 2020-06-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0004_auto_20200608_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=15, verbose_name='Lougradouro')),
                ('complemento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Complemento')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='logradouro',
        ),
        migrations.AddField(
            model_name='pedido',
            name='aceitar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Esperando restaurante'), (2, 'Em produção'), (3, 'Saiu para entrega')], default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_delivery.Endereco'),
        ),
    ]
