# Generated by Django 3.0.5 on 2020-06-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0005_auto_20200609_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default=2222, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='omplemento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
