# Generated by Django 3.0.5 on 2020-06-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0008_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
