# Generated by Django 3.0.5 on 2020-06-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0011_auto_20200612_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_delivery.Pedido')),
            ],
        ),
    ]
