# Generated by Django 3.0.5 on 2020-06-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0014_cesta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_delivery.Cliente'),
        ),
    ]
