# Generated by Django 3.0.5 on 2020-06-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0018_auto_20200613_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cesta',
        ),
        migrations.AddField(
            model_name='pedido',
            name='prato',
            field=models.ManyToManyField(to='app_delivery.Prato'),
        ),
        migrations.DeleteModel(
            name='Cesta',
        ),
    ]
