# Generated by Django 3.0.5 on 2020-06-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0019_auto_20200613_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='slug',
            field=models.SlugField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
