# Generated by Django 3.0.5 on 2020-06-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0020_prato_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='slug',
        ),
    ]
